version: "3.9"
services:
  db:
    image: mysql:5.7.38
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jobs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/conf:/opt/zookeeper-3.4.6/data

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost # Use single broker.  Only for testing.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    depends_on:
      - zookeeper
