version: "3.9"
services:
  db:
    image: mysql:5.7.38
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jobs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db